import { z } from 'zod';

/**
 * Canonical primitive schemas shared across every entity DTO.
 *
 * These are deliberately tight so that validation errors surface *before* a
 * request touches the database, the Perplexity pipeline, or the newsletter
 * provider. Keep business-specific rules here (slug shape, URL scheme, etc.)
 * so they stay consistent between the API, the admin UI, and background
 * workers.
 */

/** UUID v4/v7 — matches Postgres `uuid` columns generated by `gen_random_uuid()`. */
export const UuidSchema = z.uuid({ version: 'v4' });

/**
 * URL-safe slug: lowercase letters, digits, hyphens. No leading/trailing
 * hyphens and no consecutive hyphens. 1-120 chars matches our column width
 * budget for friendly paths.
 */
export const SlugSchema = z
  .string()
  .min(1)
  .max(120)
  .regex(
    /^[a-z0-9]+(?:-[a-z0-9]+)*$/,
    'Slug must be lowercase alphanumerics separated by single hyphens',
  );

/** Supported content locales. Must stay in sync with `locale` pgEnum. */
export const LocaleSchema = z.enum(['en', 'pt-BR', 'es']);
export type Locale = z.infer<typeof LocaleSchema>;

/** Strict https URL (http is only allowed for localhost in dev; not permitted here). */
export const UrlSchema = z
  .url()
  .max(2048)
  .refine((value) => value.startsWith('https://'), {
    message: 'URL must use https',
  });

/** Relaxed URL that allows http (used internally for things like local source links). */
export const LooseUrlSchema = z.url().max(2048);

/** Canonical email — normalised to lowercase so `citext` columns match. */
export const EmailSchema = z
  .email()
  .max(320)
  .transform((value) => value.toLowerCase());

/** Full-name / display-name style strings. */
export const NameSchema = z.string().trim().min(1).max(200);

/** Free-text body content (bio, description). */
export const ShortTextSchema = z.string().trim().min(1).max(2000);

/** `timestamptz` columns are read back as `Date` from postgres.js. */
export const TimestampSchema = z.date();

/** Same as {@link TimestampSchema} but accepts ISO strings and coerces. */
export const CoercedTimestampSchema = z.coerce.date();

/** Opaque token (confirmation/unsubscribe). Hex or base64url of reasonable length. */
export const OpaqueTokenSchema = z
  .string()
  .min(32)
  .max(256)
  .regex(/^[A-Za-z0-9_-]+$/, 'Token must be URL-safe');

/**
 * Monetary amounts stored as Postgres `numeric(12,6)` are returned as strings
 * by `postgres.js`. Validate the textual form; higher layers can convert.
 */
export const NumericStringSchema = z
  .string()
  .regex(/^-?\d+(?:\.\d+)?$/, 'Must be a decimal number');

/** Non-negative integer tokens/counts. */
export const NonNegativeIntSchema = z.int().nonnegative();

/** Positive integer (e.g. reading time minutes floors at 1). */
export const PositiveIntSchema = z.int().positive();

/**
 * Equality witness used by drift assertions.
 *
 * `StrictEqual<A, B>` resolves to `true` when the compiler treats the two
 * types as structurally identical (variance-aware), otherwise to an object
 * literal reporting the delta. Assign the result to `true` to fail the build
 * when Drizzle and Zod diverge.
 */
export type StrictEqual<A, B> =
  (<T>() => T extends A ? 1 : 2) extends <T>() => T extends B ? 1 : 2
    ? true
    : { __mismatch: true; expected: A; got: B };
